### ISSUE TITLE
Allow context options when creating a socket

### ISSUE THREAD

**Issue by elazar** [reactphp/socket-client#4]
It's not currently possible to pass in context options (e.g. [bindto](http://www.php.net/manual/en/context.socket.php)) when [creating a socket](https://github.com/reactphp/socket-client/blob/a813a91e2b13a938768c4f894c91fa8295f5b449/src/Connector.php#L35).

**Comment by clue** [comment]
:+1: for adding context options!

But first, let's see which context options are relevant here (http://php.net/manual/en/context.php):

* `socket` has a single `socket.bindto` (http://php.net/manual/en/context.socket.php)
* `ssl` has quite a few `ssl.*` (http://php.net/manual/en/context.ssl.php)

The `socket.bindto` option *could* probably be exposed through a single scalar accessor, but the `ssl.*` options probably ask for an array of options anyway. Using an array has the benefit of automatically exposing any future context options. While its very unlikely we'll see new relevant "context wrappers" here, it's very likely new "context options" will be introduced in the future.

Regarding the API, I'm not sure I like suggestion of adding another `$context` (as in #17) like this: `Connector::create($host, $port, $context)`. Let me quote from related [ticket #10](https://github.com/reactphp/socket-client/pull/10#issuecomment-109627103):

> IMO we should first figure out some use cases for this feature to see how this is actually going to be used.
>
> The socket-client component is quite lowlevel, so it's unlikely to be used by many users directly. It's probably more likely going to be used as part of some high level abstractions (say, a Redis or MySQL client implementation). These high level components depend on a `ConnectorInterface` and will likely use DI to inject this. They probably care little about *how* the connector works. Neither should they care about any "additional" parameters. They *do* care about the target (hostname and port).

As such, I don't think it makes much sense to ask your HTTP or MySQL client lib to pass in context options. As an alternative, I would suggest (somehow) assigning the context options to the connector instance itself. This makes for a more SOLID design and achieves a better separation of concerns.

**Comment by leeoniya** [comment]
just gonna add the related ref here https://github.com/reactphp/react/pull/239

**Comment by clue** [comment]
We're looking into pushing an intermediary release and will hence postpone all tickets related to context options to the next release.

See #17 and #45 for two possible implementation approaches.
