### ISSUE TITLE
Return Connection object which exposes remote address

### ISSUE THREAD

**Issue by clue** [reactphp/socket-client#44]
Each connector currently resolves with a `Stream` instance from the react/stream component. We should look into resolving with a `Connection` instance (which likely extends the `Stream` class) which should expose the remote address like this:

```
$connector->create('google.com', 80)->then(function (Connection $conn) {
    echo 'connected to ' . $conn->getRemoteAddress();
    $conn->close();
});
```

Note that the react/socket component already has a similar class (https://github.com/reactphp/socket/blob/master/src/Connection.php) which represents the server-side end of a connection.

**Comment by clue** [comment]
See also https://github.com/reactphp/react/issues/199

**Comment by samuel-allan** [comment]
Mind if I try fixing this and submitting a PR?

**Comment by clue** [comment]
I've started working on this a few months ago, finished the tests and code but didn't get to properly document this and the potential BC break. The other PRs were also certainly more pressuring back then, but this is now higher on my todo list again.

Other than that, not at all, go ahead :+1:

**Comment by samuel-allan** [comment]
Nice! I will probably now start work on the other remote addr issue (clue/php-socks-server#5)
