### ISSUE TITLE
Streams closed while data still in buffer

### ISSUE THREAD

**Issue by calcinai** [reactphp/socket-client#49]
Hey,  Not sure if this is desired behaviour or not, but I've run into an issue where the data in the buffer doesn't ever get written.

As per example:
```php
$connector->create('www.google.com', 80)->then(function (React\Stream\Stream $stream) {
    $stream->write('...');
    $stream->close();
});
```
From what I can see, the ```$stream->write()``` appends the data to the buffer and doesn't do a lot else at that point; it waits for the next tick of the event loop to come and write the buffer out.  Because of that, when you follow it immediately with ```$stream->close()```, it closes it and flushes the buffer.

As I said, I'm not sure if this is expected behaviour, and I can see benefits in both.  As a work around, I'm doing this:

```php
$connector->create('www.google.com', 80)->then(function (Stream $stream) use ($template) {
    $stream->write('…');
    $stream->getBuffer()->on('full-drain', function() use($stream) {
        $stream->close();
    });
});
```

Is this as simple as a doc update?

**Comment by clue** [comment]
> Is this as simple as a doc update?

Yes, this is expected behavior and hence a rather pointless example :-)

Using `end()` instead of `close()` would likely resolve this here, I suppose?

Other than that, we should probably add some documentation to the [stream component](https://github.com/reactphp/stream/) and link there. What do you think?

**Comment by calcinai** [comment]
Yeah, that actually makes sense once reading the stream documentation.  It all totally makes sense to function the way it does, so I guess just updating the example would be the best thing to do.

Thanks for clarifying this for me.

**Comment by clue** [comment]
Thanks for reporting back @calcinai.

The documentation has now been updated via #46, so I suppose this can be closed :+1:
