### ISSUE TITLE
SNI_server_name is deprecated

### ISSUE THREAD

**Issue by flip111** [reactphp/socket-client#56]
while getting https://groups.google.com/forum/feed/elm-discuss/msgs/atom.xml?num=50 i get this:

Error executing request: exception 'UnexpectedValueException' with message 'Unable to complete SSL/TLS handshake: SNI_server_name is deprecated in favor of peer_name' in vendor\react\socket-client\src\StreamEncryption.php:108

I'm not using this library directly but as a dependency of https://github.com/phergie/phergie-irc-plugin-react-feedticker

**Comment by clue** [comment]
Thanks for reporting @flip111. This (only) happens in PHP 5.6+, see also https://github.com/composer/composer/issues/2887.

I'll look into filing a PR to fix this and add a test case.
