### ISSUE TITLE
loop response

### ISSUE THREAD

**Issue by dolphin4ik** [reactphp/socket-client#58]
Hello!
May be I`m noob, but how may I read (use) response in loop?
My server broadcasts every 5-30 sec some data. How to cache this data?

**Comment by clue** [comment]
Hi @dolphin4ik! Each `ConnectorInterface` resolves with a `Stream` instance that behaves like a normal stream: https://github.com/reactphp/stream

```
$connector->create($host, $port)->then(function(Stream $stream) {
    $stream->on('data', function ($chunk) {
        var_dump($chunk);
    });
    $stream->on('close', function() {
        echo 'CLOSED';
    });
});
```

I hope this helps to get you started :+1:
