### ISSUE TITLE
False positive connection

### ISSUE THREAD

**Issue by cboden** [reactphp/socket-client#63]
```php
<?php

require __DIR__ . '/vendor/autoload.php';
$loop = \React\EventLoop\Factory::create();

$tcpConnector = new React\SocketClient\TcpConnector($loop);

$tcpConnector->create('127.0.0.1', 8080)->then(function (React\Stream\Stream $stream) {
    echo "Connected\n";
}, function() {
    echo "Failed\n";
});

$loop->run();
```

Have no service listening to port 8080 (or any port to attempt to connect to), run script. Result is `Connected`, expected `Failed`.

**Comment by clue** [comment]
This is also covered by our test suite: https://github.com/reactphp/socket-client/blob/f905ec2a576b1242b10d5c1dbd2f0eb4fcea7f0c/tests/TcpConnectorTest.php#L12-L21

Are you sure there's nothing listening on this port? :-)

```bash
$ sudo netstat -tulpn | grep :8080
```

**Comment by cboden** [comment]
> netstat: n: unknown or uninstrumented protocol

I found the issue however...I have a VirtualBox instance that is forwarding 8080 to a guest OS **but** the guest OS doesn't have a service listening to the forwarded port. I'm not sure what state the host port is in, but it's not connectable...`telnet 127.0.0.1 8080` returns:
> Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.

**Comment by clue** [comment]
> it's not connectable
> Connected to localhost.
> Connection closed by foreign host.

This means the port is in fact open and you just did connect successfully. And after connecting, the server immediately closed your connection.

FWIW: You can also reproduce this with a simple server like this:

```php
$server = new Server($loop);
$server->on('connection', function ($conn) {
    $conn->close();
});
$server->listen(8080);
```

This behavior is in line with how all low-level socket functions work (`socket_connect()`, `fsockopen()`, `stream_socket_client()` etc.), so I'm all keeping this as-is.

**Comment by cboden** [comment]
ugh...I didn't have a close handler in my lib until after the higher level protocol was established...totally missed a close call was being emitted from the stream
