### ISSUE TITLE
[Question] Can I Query LDAP after successfully connecting?

### ISSUE THREAD

**Issue by tokidoki11** [reactphp/socket-client#67]
I Use Secure Gateway service on bluemix thus I connect to the securegateway by using SecureConnector. 

It shows connection estabilished.
So can I query LDAP using $stream or anything after connecting?
Thanks

**Comment by clue** [comment]
Each connector resolves with a `$stream` instance that can be used to send any raw TCP/IP data you wish. This means that yes, you can build the LDAP protocol on top of this. No such implementation does currently exist, to my knowledge.

Many other protocols have been built on top of this component, so if you're looking for some pointers on how to start, you may wish to check https://github.com/reactphp/react/wiki/Users

I hope this helps :+1:
