### ISSUE TITLE
Keep connection open

### ISSUE THREAD

**Issue by aali1** [reactphp/socket-client#68]
Hi,

I have question regarding the capability of this library. Does this library works for Http Streaming connections?

Currently, I'm using a solution with fockopen and while($feof($fp)) to wait until server closes the connection or timeout.

**Comment by clue** [comment]
This library helps with establishing a TCP/IP connection and then returns a `Stream` which you can use to pipe any kind of data through. It's entirely up to you to "keep the connection open".

If you're looking for a HTTP client library, you may want to look into using the [HttpClient component](https://github.com/reactphp/http-client). It does support HTTP streaming, however it does not currently support HTTP connection reuse (`Connection: keep-alive`). PRs are welcome, I suppose? :+1: 

I hope this helps! :+1:
