### ISSUE TITLE
Abandon package on packagist

### ISSUE THREAD

**Issue by maciejmrozinski** [reactphp/socket-client#96]
@clue Shouldn't we mark `react/socket-client` as `abandoned` on packagist.org and redirect people to `react/socket`?

**Comment by WyriHaximus** [comment]
@maciejmrozinski in the long run yes, but currently, without our own packages moved over, that would freak out our users. ([For reference see this.](https://github.com/ratchetphp/Ratchet/issues?utf8=%E2%9C%93&q=is%3Aissue%20guzzle%20abandoned%20)) My personal preference would be to deprecate it now and say still port bug fixes for another year and from there only security fixes for a year before abandoning it on packagist.

**Comment by maciejmrozinski** [comment]
I can clearly see Your point, especially with reference posted :D Thx for response.

**Comment by clue** [comment]
This package has just been abandoned with react/socket being the recommended replacement as per #86 :muscle:
