### ISSUE TITLE
Connector 怎么实现重连机制

### ISSUE THREAD

**Issue by cenwj** [reactphp/socket-client#97]
Connector 怎么实现重连机制

**Comment by WyriHaximus** [comment]
Judging by the result of google translate you want to implement reconnecting. You can achieve this to listen on the `close` and `error` events on the open connection and open an new connection when either is fired.

**Comment by clue** [comment]
I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:
